name: Deploy

on:
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read 
defaults:
  run:
    working-directory: "./hello_world"
env:
  PYTHON_VERSION: 3.13
  function-name: sample-actions-deploy-function
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ env.PYTHON_VERSION }}' 
      - name: Build
        run: pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.deploy_role }}
          aws-region: ap-northeast-1
      
      - name: Deploy
        uses: aws-actions/aws-lambda-deploy@v1.0.1
        with:
          function-name: ${{ env.function-name }}
          code-artifacts-dir: ./
          handler: app.lambda_handler
          runtime: python${{ env.PYTHON_VERSION }}