name: Deploy

on:
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read 
defaults:
  run:
    working-directory: "./hello_world"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: pip install -r requirement.txt && python -m build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.deploy_role }}
          aws-region: ap-northeast-1
      
      - name: Deploy
        uses: aws-actions/aws-lambda-deploy@v1.0.1
        with:
          function-name: my-function-name
          code-artifacts-dir: ./
          handler: app.lambda_handler
          runtime: python3.12